CREATE DATABASE RAFFLE;
USE RAFFLE;

CREATE TABLE auction (
    AUCTION_ID     INT  NOT NULL AUTO_INCREMENT, 
    AUCTION_NAME   VARCHAR(40)  NOT NULL,
    PRIZE_COUNT INT NOT NULL,
    CREATED_ON  DATE NOT NULL,
    CREATED_BY VARCHAR(40),
    UPDATED_ON DATE NOT NULL,
    UPDATED_BY VARCHAR(40),
	START_DATE  DATE NOT NULL,
	START_TIME  TIME NOT NULL,
    END_DATE  DATE NOT NULL,
	END_TIME  TIME NOT NULL,
    DRAWING_DATE  DATE NOT NULL,
	DRAWING_TIME  TIME NOT NULL,
    MIN_TICKETS INT NOT NULL,
    MAX_TICKETS INT NOT NULL,
    PRIMARY KEY (AUCTION_ID),                
    UNIQUE  KEY (AUCTION_NAME)               
);

CREATE TABLE product (
	 PRODUCT_ID    INT  NOT NULL AUTO_INCREMENT, 
     PRODUCT_NAME   VARCHAR(40)  NOT NULL,
     PRODUCT_CATEGORY   VARCHAR(100)  NOT NULL,
     PRODUCT_IMAGE VARCHAR(100)  NOT NULL,
     PRODUCT_VIDEO VARCHAR(100)  NOT NULL,
     PRODUCT_DESC VARCHAR(100)  NOT NULL,
	 CREATED_ON  DATE NOT NULL,
     CREATED_BY VARCHAR(40),
     UPDATED_ON DATE NOT NULL,
     UPDATED_BY VARCHAR(40),
     PRIMARY KEY (PRODUCT_ID),                
     UNIQUE  KEY (PRODUCT_NAME)               
);


CREATE TABLE users (
	 USER_ID    INT  NOT NULL AUTO_INCREMENT, 
     USER_NAME   VARCHAR(40)  NOT NULL,
     WALLET_ID    INT,
     EMAIL   VARCHAR(40)  NOT NULL,
     PHONE VARCHAR(40)  NOT NULL,
     ADDRESS VARCHAR(100)  NOT NULL,
	 CREATED_ON  DATE NOT NULL,
     CREATED_BY VARCHAR(40) NOT NULL,
     UPDATED_ON DATE,
     UPDATED_BY VARCHAR(40),
     PRIMARY KEY (USER_ID),                
     UNIQUE  KEY (USER_NAME)               
);


CREATE TABLE user_auction (
	 USER_ACTION_ID INT  NOT NULL AUTO_INCREMENT, 
     USER_ID_FK    INT  NOT NULL, 
     AUCTION_ID_FK   INT NOT NULL,
     CREATED_ON  DATE NOT NULL,
     STATUS CHAR(1),
     PRIMARY KEY (USER_ACTION_ID)                
);

ALTER TABLE user_auction ADD FOREIGN KEY (USER_ID_FK) REFERENCES users(USER_ID);
ALTER TABLE user_auction ADD FOREIGN KEY (AUCTION_ID_FK) REFERENCES auction(AUCTION_ID);


CREATE TABLE auction_tickets (
	AUCTION_TICKETS_ID  INT  NOT NULL AUTO_INCREMENT, 
    AUCTION_ID_FK  INT  NOT NULL, 
    TICKET_ID   INT  NOT NULL,
    USER_ID_FK INT NOT NULL,
    CREATED_ON  DATE NOT NULL,
    UNIQUE (AUCTION_ID_FK,TICKET_ID),
    PRIMARY KEY (AUCTION_TICKETS_ID)
);

ALTER TABLE auction_tickets ADD FOREIGN KEY (AUCTION_ID_FK) REFERENCES auction(AUCTION_ID);
ALTER TABLE auction_tickets ADD FOREIGN KEY (USER_ID_FK) REFERENCES users(USER_ID);

CREATE UNIQUE INDEX auction_tickets_unique ON auction_tickets (AUCTION_ID_FK,TICKET_ID);


CREATE TABLE auction_prize_details(
	AUCTION_PRIZE_ID  INT  NOT NULL AUTO_INCREMENT,
    AUCTION_ID_FK INT NOT NULL,
    PRIZE_POSITION INT NOT NULL,
    PRIZE_INDEX INT NOT NULL,
    PRODUCT_ID_FK  INT,
	WINNER_ID_FK  INT,
	TICKET_ID  INT,
    CREATED_ON  DATE NOT NULL,
    CREATED_BY VARCHAR(40),
    UPDATED_ON DATE,
    UPDATED_BY VARCHAR(40),
    PRIMARY KEY (AUCTION_PRIZE_ID),
    UNIQUE  KEY (AUCTION_ID_FK,PRIZE_POSITION,PRIZE_INDEX)
);


ALTER TABLE auction_prize_details ADD FOREIGN KEY (AUCTION_ID_FK) REFERENCES auction(AUCTION_ID);  
ALTER TABLE auction_prize_details ADD FOREIGN KEY (PRODUCT_ID_FK) REFERENCES product(PRODUCT_ID);
ALTER TABLE auction_prize_details ADD FOREIGN KEY (WINNER_ID_FK) REFERENCES users(USER_ID);

CREATE UNIQUE INDEX auction_prize_details_unique ON auction_prize_details (AUCTION_ID_FK,PRIZE_POSITION,PRIZE_INDEX); 


---


INSERT INTO users(USER_NAME,WALLET_ID,EMAIL,PHONE,ADDRESS,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('JOHN',123,'john@gmail.com','91-3331212','12,VOC Streat','2023-01-26','ADMIN','2023-01-26','ADMIN');

INSERT INTO users(USER_NAME,WALLET_ID,EMAIL,PHONE,ADDRESS,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('THOMOS',456,'thomos@gmail.com','91-33324244','77,KAMARAJ Streat','2023-01-26','ADMIN','2023-01-26','ADMIN');

INSERT INTO users(USER_NAME,WALLET_ID,EMAIL,PHONE,ADDRESS,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('NEWTON',776,'newton@gmail.com','91-33324233','66,KATKAN Streat','2023-01-26','ADMIN','2023-01-26','ADMIN');

INSERT INTO users(USER_NAME,WALLET_ID,EMAIL,PHONE,ADDRESS,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('SMITH',766,'smith@gmail.com','91-33324222','22,KATTABOMMAN Streat','2023-01-26','ADMIN','2023-01-26','ADMIN');

INSERT INTO users(USER_NAME,WALLET_ID,EMAIL,PHONE,ADDRESS,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('PAUL',556,'paul@gmail.com','91-33324111','10,THERASA Streat','2023-01-26','ADMIN','2023-01-26','ADMIN');

INSERT INTO users(USER_NAME,WALLET_ID,EMAIL,PHONE,ADDRESS,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('STEPHEN',333,'stephen@gmail.com','91-33324000','20,BHARATHIYAR Streat','2023-01-26','ADMIN','2023-01-26','ADMIN');


---

INSERT INTO product(PRODUCT_NAME,PRODUCT_CATEGORY,PRODUCT_IMAGE,PRODUCT_VIDEO,PRODUCT_DESC,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('Benz Car','Cars','Benz Car','Benz Car','Benz Car','2023-01-26','ADMIN','2023-01-26','ADMIN');

INSERT INTO product(PRODUCT_NAME,PRODUCT_CATEGORY,PRODUCT_IMAGE,PRODUCT_VIDEO,PRODUCT_DESC,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('BMW Car','Bike','BMW Car','BMW Car','BMW Car','2023-01-26','ADMIN','2023-01-26','ADMIN');

INSERT INTO product(PRODUCT_NAME,PRODUCT_CATEGORY,PRODUCT_IMAGE,PRODUCT_VIDEO,PRODUCT_DESC,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('Audi Car','Cars','Audi Car','Audi Car','Audi Car','2023-01-26','ADMIN','2023-01-26','ADMIN');

INSERT INTO product(PRODUCT_NAME,PRODUCT_CATEGORY,PRODUCT_IMAGE,PRODUCT_VIDEO,PRODUCT_DESC,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('Adidas Shoe','Sporting Goods','Adidas Shoe','Adidas Shoe','Adidas Shoe','2023-01-26','ADMIN','2023-01-26','ADMIN');

INSERT INTO product(PRODUCT_NAME,PRODUCT_CATEGORY,PRODUCT_IMAGE,PRODUCT_VIDEO,PRODUCT_DESC,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('Nike Shoe','Sporting Goods','Nike Shoe','Nike Shoe','Nike Shoe','2023-01-26','ADMIN','2023-01-26','ADMIN');

INSERT INTO product(PRODUCT_NAME,PRODUCT_CATEGORY,PRODUCT_IMAGE,PRODUCT_VIDEO,PRODUCT_DESC,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('Ninety Cycle','Sporting Goods','Ninety Cycle','Ninety Cycle','Ninety Cycle','2023-01-26','ADMIN','2023-01-26','ADMIN');

INSERT INTO product(PRODUCT_NAME,PRODUCT_CATEGORY,PRODUCT_IMAGE,PRODUCT_VIDEO,PRODUCT_DESC,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('Hercules Cycle','Sporting Goods','Hercules Cycle','Hercules Cycle','Hercules Cycle','2023-01-26','ADMIN','2023-01-26','ADMIN');

INSERT INTO product(PRODUCT_NAME,PRODUCT_CATEGORY,PRODUCT_IMAGE,PRODUCT_VIDEO,PRODUCT_DESC,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('RTFKT','NFT','RTFKT','RTFKT','RTFKT','2023-01-26','ADMIN','2023-01-26','ADMIN');

INSERT INTO product(PRODUCT_NAME,PRODUCT_CATEGORY,PRODUCT_IMAGE,PRODUCT_VIDEO,PRODUCT_DESC,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('Damien Hirst','NFT','Damien Hirst','Damien Hirst','Damien Hirst','2023-01-26','ADMIN','2023-01-26','ADMIN');


INSERT INTO product(PRODUCT_NAME,PRODUCT_CATEGORY,PRODUCT_IMAGE,PRODUCT_VIDEO,PRODUCT_DESC,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('Bike','Bike','Bike','Bike','Bike','2023-01-26','ADMIN','2023-01-26','ADMIN');

INSERT INTO product(PRODUCT_NAME,PRODUCT_CATEGORY,PRODUCT_IMAGE,PRODUCT_VIDEO,PRODUCT_DESC,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
VALUES('Laptop','Computer','Laptop','Laptop','Laptop','2023-01-26','ADMIN','2023-01-26','ADMIN');


--

SELECT * FROM product where product_id = 1;
SELECT * FROM users where user_id = 1;
SELECT * FROM auction where auction_id = 1;
SELECT * FROM auction_prize_details where auction_id_fk=1;
SELECT * FROM auction_tickets where auction_id_fk=1;
SELECT * FROM auction_tickets where auction_id_fk=1 and user_id_fk = 1;

--

DROP TABLE auction_prize_details;
DROP TABLE auction_tickets;
DROP TABLE user_auction;
DROP TABLE users;
DROP TABLE product;
DROP TABLE auction;

